### PR TITLE
Adding more options to modify

### PR DESCRIPTION
**Pull request by lfrancioli**
*  Added options to udpate cluster size / max-idle
* Renamed modify -> update to match GCP terminology
* Added option to connect to rstudio on GCE with cluster connect

### CODE REVIEW

**Comment by tpoterba** [comment]
how is RStudio installed?

**Comment by lfrancioli** [comment]
Up to the user :)
This is just the default port and since Rstudio is more of a GCE type of service than dataproc, I removed the `-m` appending at the end of the instance name. 

Thinking about it, maybe it'd be better to make it more general and implement a `--service-port` option to choose whatever port we want. And maybe a `--gce` option that would not append the `-m`

Thoughts?

Note that I could also strip that part and keep only the `update` part. I personally use `update` all the  time.

**Comment by lfrancioli** [comment]
update is very useful -- not sure what's the case for closing this.

**Comment by tpoterba** [comment]
I think this is a good change, aside from the breaking rename change, which I'm not sure is necessary (Though I agree would be more consistent if we had chosen that originally)

we already have deviations from gcloud e.g. start/create

**Comment by tpoterba** [comment]
I also feel like if we have an rstudio port we should have a way to install it at cluster creation

**Comment by danking** [comment]
Heh, tim reminded me this was assigned to me.

**Comment by danking** [comment]
Ok, I'll approve if:

1. it is rebased

2. we do not rename, or we keep both names. I refuse to break backwards compatibility, we do that too often already.

**Comment by lfrancioli** [comment]
OK great!

I'll rebased and  remove the rstudio bit. Regarding the naming issue, we  could keep `modify` to specifically change the hail version and  `update` to actually update  the cluster.  
I really think that updating the cluster  should be `update` to be similar to `gcloud`

**Comment by lfrancioli** [comment]
Although it  seems like  it's a 2vs1 on the naming issue :)

**Comment by danking** [comment]
I haven't looked closely, but having both `modify` and `update` call the exact same code (we can keep it in `update.py`) seems like the best solution here.

**Comment by tpoterba** [comment]
I spent an hour looking at argparse when I first looked at this PR, and decided it's not easy to alias subparsers. Not sure what to do, knowing that.

**Comment by lfrancioli** [comment]
OK fine, let's just keep `modify`...

**Comment by tpoterba** [comment]
I think it's a good change, but we should bunch together several renames at some point in the future.

**Pull request merged**
