### PR TITLE
update to 3.0.0

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by cseed** [comment]
Oops, sorry I missed this.  This should go in.  Rebase?

Also, we broke the 2.0.x version since devel => 0.2 went in: https://github.com/Nealelab/cloudtools/commit/c49bb905d3ba4d791150c3627c3c9ebde006a55a.

Need to sync the repos and get all the version numbers in one place.

**Comment by danking** [comment]
Cloudtools depends on a configuration file `gs://hail-common/builds/0.1/latest-hash/cloudtools-3-spark-2.0.2.txt`. That file exists for the 2.x.x series. cc: @catoverdrive

**Comment by danking** [comment]
There should also be a devel/0.2 config file.

**Comment by tpoterba** [comment]
I'm very confused. Does this mean we need a 2-phase commit again?

**Comment by tpoterba** [comment]
https://github.com/hail-is/hail/pull/4672

**Comment by tpoterba** [comment]
it looks like this is only for hail versions, not cloudtools versions?

**Comment by tpoterba** [comment]
it looks like this is only for hail versions, not cloudtools versions?

**Comment by cseed** [comment]
Will cloudtools branches not get re-tested when the Hail repo updates?

**Comment by danking** [comment]
They do not get retested when the hail repo changes. The CI is unaware of this dependency. We need to fold this repo into hail-is/hail.

**Comment by cseed** [comment]
Want to push an empty commit to bump CI?  You can do it with `git commit --allow-empty -m bump`.

**Comment by danking** [comment]
You have to trigger a redeploy of hail first. Hail hasn't been changed.

**Comment by tpoterba** [comment]
can you clarify what you mean, Dan? We committed a change to Hail yesterday to use cloudtools version 3

**Comment by danking** [comment]
I think it should be good now.

**Pull request merged**
