### PR TITLE
Add python files or folders from environment variable; zip files together

### PR DESCRIPTION
**Pull request by konradjk**
Merging the rest of the important stuff from https://github.com/macarthur-lab/gnomad_hail/blob/master/pyhail.py here

### CODE REVIEW

**Comment by tpoterba** [comment]
update pip version so it gets deployed on merge?

**Comment by danking** [comment]
this is unassigned, I'm gonna roll for someone, but @tpoterba you can take it if you prefer.

**Comment by catoverdrive** [comment]
basically, I really like this change but am slightly uncomfortable with the fact that it will silently discard non-python files, given that I don't think this is the current behavior, but maybe there's a thing that I'm missing where it doesn't make sense to use it for other types of files?

**Comment by konradjk** [comment]
I have no strong opinion, but AFAIK the only files you'd actually want to use here are ones that you import using your code. Perhaps uploading custom files is something someone might want, but I'm not exactly sure how (if?) someone could point to that file

**Pull request merged**
