### PR TITLE
Allows connecting to multiple notebooks on distinct clusters

### PR DESCRIPTION
**Pull request by lfrancioli**
clusters need to be in the same project.

### CODE REVIEW

**Comment by lfrancioli** [comment]
@konradjk -- is this something you can review?

**Comment by konradjk** [comment]
I'd rather not: @danking and @tpoterba have more experience than I do with the networking side of things here and can comment if there are any issues.

Also, be aware this repo is not long for this world, as https://github.com/hail-is/hail/pull/6010 is now open - @tpoterba is that expected to go through soon?

**Comment by lfrancioli** [comment]
well, seems like for now this is still the repo for now :)

And hopefully @danking or @tpoterba can take a look! It's a functionality that quite a few peeps have been asking for.

**Comment by tpoterba** [comment]
moved to hail-is/hail

**Pull request closed without merging**
