### PR TITLE
Pin dependency versions

### LINKED ISSUE #104: cloud tools is broken for hail 0.1
See: [dataproc-initialization-script-1_output.log](https://github.com/Nealelab/cloudtools/files/2424771/dataproc-initialization-script-1_output.log)

The issue is due to new versions of python packages being incompatible with python 2.x. Fourteen hours ago, [ipykernel jumped to 5.0.0](https://github.com/ipython/ipykernel/releases) and eliminated python 2.x support. matplotlib 3.0.0 eliminated python 3 support [10 days ago](https://github.com/matplotlib/matplotlib/releases). IPython 6 has not supported python 3 [for over a year](https://ipython.readthedocs.io/en/stable/whatsnew/version6.html#ipython-6-0), so I'm not sure how that's been working correctly.

Moreover, if you carefully investigate that log, you will see that we do not fail if the conda or pip install commands fail. The failure was coming from later in the python setup script.

### PR DESCRIPTION
**Pull request by danking**
resolves #104

### CODE REVIEW

**Comment by danking** [comment]
Hrm. @tpoterba The CI is failing because the deployed cloud tools init_notebook1.py is broken. Thoughts on shipping this file with cloud tools? Is the issue that you can't use a local file as an initialization action?

**Comment by tpoterba** [comment]
> Is the issue that you can't use a local file as an initialization action

I believe so, yes

**Comment by danking** [comment]
Almost all of the file is shared at this point, so I don't think separating it buys us much clarity.

**Comment by danking** [comment]
I copied the current version to the cloud, so hopefully the tests will pass now.

**Pull request merged**
