### PR TITLE
Adding support for GRCh38 VEP

### LINKED ISSUE #37: --vep for hg38
would be possible to have an extra option for the --vep argument to indicate which genome reference to use for running vep? 
for example `--vep 37` or `--vep 38`

### PR DESCRIPTION
**Pull request by konradjk**
Still moving files over, so no need to merge yet, but this will be the general idea

Resolves #37

### CODE REVIEW

**Comment by konradjk** [comment]
Resolves #37

**Comment by tpoterba** [comment]
what is this draft stuff?

**Comment by tpoterba** [comment]
cool.

**Comment by konradjk** [comment]
If anyone is testing this out, the recommended config for 38 is: `gs://hail-common/vep/vep/vep95-GRCh38-loftee-gcloud.json` - I'll put this into a separate PR into hail docs later

**Pull request merged**
